image: node:10

stages:
  - release

.base:
  tags:
    - smartive

release generator:
  extends: .base
  stage: release
  before_script:
    - npm ci
  script:
    - npx semantic-release
  only:
    - master

deploy docker image:
  extends: .base
  stage: release
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_FILE: ./Dockerfile
    DOCKER_CONTEXT: "."
    DOCKER_BUILDKIT: "1"
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build --file $DOCKER_FILE -t smartive/mockserver:$CI_COMMIT_TAG $DOCKER_CONTEXT
    - docker tag smartive/mockserver:$CI_COMMIT_TAG smartive/mockserver:latest
  after_script:
    - docker push smartive/mockserver:$CI_COMMIT_TAG
    - docker push smartive/mockserver:latest
  only:
    - tags
