include:
  - project: 'smartive/ci-templates'
    ref: v1.4.1
    file: '/all-templates.yml'

stages:
  - release

create release:
  stage: release
  extends: .create-release
  only:
    - master

deploy docker image:
  extends: .gitlab-docker
  stage: release
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build --file $DOCKER_FILE -t smartive/mockserver:$CI_COMMIT_TAG $DOCKER_CONTEXT
    - docker tag smartive/mockserver:$CI_COMMIT_TAG smartive/mockserver:latest
  after_script:
    - docker push smartive/mockserver:$CI_COMMIT_TAG
    - docker push smartive/mockserver:latest
  only:
    - tags
